### ISSUE TITLE
[Feature Req] resize sidebar when you have a single column

### ISSUE THREAD

**Issue by ctf0** [markalfred/sublime-pane-resizer#10]
currently the plugin work when there are 2 or more columns , but what if u only have a single column, now the plugin will resize the sidebar instead so u dont need to use the mouse 👍

**Comment by markalfred** [comment]
Thanks for the request @ctf0! As far as I've been able to find, though, the only things a plugin can do with the sidebar, according to Sublime's current API, are set it to visible/invisible and ask whether it's currently visible (see `is_sidebar_visible` and `set_sidebar_visible` [here](http://www.sublimetext.com/docs/3/api_reference.html#sublime.Window)).

So I think this would be impossible. In the future, if Sublime expands their API to allow the sidebar's size to be edited, I'd love to add this feature. Thank you for the suggestion!
