### ISSUE TITLE
Windows alt+tab overrides pane cycling

### ISSUE THREAD

**Issue by andytill** [markalfred/sublime-pane-resizer#7]
On Win 8 the default pane cycling shortcut `ctrl + alt + tab` is overridden by Windows' app cycling.  Changed to `ctrl + alt + n` (n for next) in my user settings to make this work correctly.

Suggest that the default shortcut should be different for windows so it works out the box.

**Comment by markalfred** [comment]
Thanks for letting me know!

Since `next_view` is `ctrl+pageup`, my go-to would likely be `alt+pageup` and `alt+pagedown` for Windows users.

**Comment by andytill** [comment]
No worries.  The plugin is great.  `alt+pageup/pagedown` is more sensible.

Just noticed that gnome 3 also uses alt + tab for cycling through open apps, maybe pageup/pagedown should be the standard for linux as well.

**Comment by markalfred** [comment]
:+1:
